### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by madchap** [Vincit/logspout-gelf#2]
Hey

First of all, thanks for taking the pain out of rebuilding an image :)

Container started with
`$ docker run --name logspout --volume=/var/run/docker.sock:/var/run/docker.sock -h $(hostname -s) --restart=unless-stopped vincit/logspout-gelf gelf://192.168.10.206:12201`

I just had a weird occurence, when logspout-gelf crashed with the following trace:

```
# logspout v3.2.4 by gliderlabs                                                                                    
# adapters: syslog tcp udp tls gelf raw                                                                            
# options : persist:/mnt/routes                                                                                    
# jobs    : routes http[logs,routes]:80 pump                                                                       
# routes  :                                                                                                        
#   ADAPTER     ADDRESS                 CONTAINERS      SOURCES OPTIONS                                            
#   gelf        192.168.10.206:12201                            map[]                                              
panic: runtime error: slice bounds out of range                                                                    
                                                                                                                   
goroutine 9 [running]:                                                                                             
github.com/micahhausler/logspout-gelf.GelfMessage.getExtraFields(0xc42027a300, 0xc4202b3e88, 0x1, 0x0, 0x0, 0x0)   
        /go/src/github.com/micahhausler/logspout-gelf/gelf.go:95 +0x78f                                            
github.com/micahhausler/logspout-gelf.(*GelfAdapter).Stream(0xc42005f2b0, 0xc420084540)                            
        /go/src/github.com/micahhausler/logspout-gelf/gelf.go:53 +0xc9                                             
github.com/gliderlabs/logspout/router.(*RouteManager).route(0xc420026640, 0xc4200ca370)                            
        /go/src/github.com/gliderlabs/logspout/router/routes.go:160 +0xb3                                          
github.com/gliderlabs/logspout/router.(*RouteManager).Run.func1(0xc420026640, 0xc4200ca370)                        
        /go/src/github.com/gliderlabs/logspout/router/routes.go:186 +0x35
created by github.com/gliderlabs/logspout/router.(*RouteManager).Run
        /go/src/github.com/gliderlabs/logspout/router/routes.go:185 +0xe8
```

I'll keep watching if it happens again. I don't know what triggered that error.

Thanks,

**Comment by ghost** [comment]
Thanks for finding our image valuable!

And thanks for reporting the bug. We also found the exactly same issue on some of our Logspout instances, but not all.

This issue was fixed on micahhausler/logspout-gelf adapter's [commit](https://github.com/micahhausler/logspout-gelf/commit/440a1c31cdb17e0583fbc662579df2ab655423fc) on 26th of April 2018.

I rebuilt our image and pushed new versions to Docker Hub.

You should try to pull new image and recreate the Logspout-gelf instance. For us this fixed the problem. Hoping you are also as lucky!

- Timo
